---
- name: include targets tasks
  ansible.builtin.include_tasks:
    file: node.yml
  when:
    - monitoring_targets_inventory_group in group_names

- name: include pgsql_monitoring
  ansible.builtin.include_tasks:
    file: postgres.yml
  when:
    - inventory_hostname is {{monitoring_pgsql_db_host}}

- name: include server tasks
  ansible.builtin.include_tasks:
    file: server.yml
  when:
    - monitoring_server_inventory_group in group_names
