---

- name: Create a network
  community.docker.docker_network:
    name: "{{ monitoring_docker_network_name }}"
    ipam_config:
      - subnet: "{{ monitoring_docker_network_subnet | ansible.utils.ipsubnet }}"
        gateway: "{{ monitoring_docker_network_subnet | ansible.utils.ipaddr('next_usable') }}"

- name: Run Cadvisor via docker
  docker_container:
    name: cadvisor
    image: "{{ monitoring_cadvisor_image }}"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "{{ monitoring_cadvisor_port }}:8080"
    networks:
      - name: "{{ monitoring_docker_network_name }}"
        aliases:
          - cadvisor
    restart_policy: always
  when: monitoring_cadvisor_enabled | bool
