- name: Run postresql_exporter via docker
  docker_container:
    name: monitoring_postgresql
    image: "quay.io/prometheuscommunity/postgres-exporter:v0.10.0"
    env: "{{ monitoring_pgsql_parameters | default ({}) }}"
    ports:
      - "{{ monitoring_pgsql_exporter_port }}:{{ monitoring_pgsql_exporter_port }}"
    networks:
      - name: "{{ monitoring_docker_network_name }}"
        aliases:
          - pg_exporter
    restart_policy: always
  when: monitoring_pgsql_exporter_enabled | bool
  tags: ['pg_exporter']
