---
# tasks file for monitoring_server
# install prometheus + grafana + alertmanager via docker-compose with alerting     
- name: make directory  
  file: 
    path: "{{ monitoring_config_dir }}"
    state: directory
    mode: '0755' 
     
# generating configs for prometheus + grafana + alertmanager + whatever
- name: generating configs prometheus
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644" 
  loop:
     -  { src: "prometheus.yml.j2" , dest: "{{ monitoring_config_dir }}/prometheus.yml" }
     -  { src: "alert_rules.yml.j2" , dest: "{{ monitoring_config_dir }}/alert_rules.yml" }
  notify: 
     - restart_prometheus

- name: generating configs alertmanager
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
     -  { src: "alertmanager.yml.j2" , dest: "{{ monitoring_config_dir }}/alertmanager.yml" }
  notify: 
     - restart_alertmanager

- name: generating configs blackbox
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644" 
  loop:
     -  { src: "blackbox.yml.j2" , dest: "{{ monitoring_config_dir }}/blackbox.yml" }
  notify: 
     - restart_blackbox

- name: generating docker-compose
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644" 
  loop:
     -  { src: "docker-compose.yml.j2" , dest: "{{ monitoring_config_dir }}/docker-compose.yml" }

- name: Create a network
  community.docker.docker_network:
    name: "{{ monitoring_docker_network_name }}"
    ipam_config:
      - subnet: "{{ monitoring_docker_network_subnet | ansible.utils.ipsubnet }}"
        gateway: "{{ monitoring_docker_network_subnet | ansible.utils.ipaddr('next_usable') }}"
  notify:
    - restart_stand


- name: run deploy
  community.docker.docker_compose:
    project_name: "monitoring" 
    project_src: "{{ monitoring_config_dir }}/"
  tags: ['prometheus']
