---
# handlers file for monitoring_server
- name: restart_prometheus
  community.docker.docker_compose:
    project_name: "monitoring"
    project_src: "{{ monitoring_config_dir }}/"
    build: false
    services: 
      - prometheus
    restarted: true

- name: restart_alertmanager
  community.docker.docker_compose:
    project_name: "monitoring"
    project_src: "{{ monitoring_config_dir }}/"
    build: false
    services: 
      - alertmanager
    restarted: true

- name: restart_blackbox
  community.docker.docker_compose:
    project_name: "monitoring"
    project_src: "{{ monitoring_config_dir }}/"
    build: false
    services: 
      - blackbox
    restarted: true

- name: restart_stand
  community.docker.docker_compose:
    project_name: "monitoring"
    project_src: "{{ monitoring_config_dir }}/"
    build: false
    restarted: true

- name: restart_processes_exporter
  docker_container:
    name: monitoring_process_exporter
    image: "{{ monitoring_process_exporter_image }}"
    privileged: true
    state: started
    restart: true
    volumes:
      - "/proc:/host/proc"
      - "{{ monitoring_config_dir }}/process-exporter.yml:/config/process-exporter.yml"
    command:
      - "--procfs=/host/proc"
      - "--config.path=/config/process-exporter.yml"
    ports:
      - "{{ monitoring_process_exporter_port }}:{{ monitoring_process_exporter_port }}"
    networks:
      - name: "{{ monitoring_docker_network_name }}"
        aliases:
          - process_exporter
  tags: ['process_exporter']
