---
role_name_check: 1
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: Ubuntu-20.04
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
